# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160623_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='main_task_id',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='icpcheck',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 27, 11, 36, 1, 846832), null=True),
        ),
        migrations.AlterField(
            model_name='subdomainbrute',
            name='fuzz_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 27, 11, 36, 1, 847367), null=True),
        ),
    ]
