# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160627_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task_id',
            new_name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='icpcheck',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 27, 13, 21, 19, 800954), null=True),
        ),
        migrations.AlterField(
            model_name='subdomainbrute',
            name='fuzz_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 27, 13, 21, 19, 801518), null=True),
        ),
    ]
