# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160712_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burp',
            name='path',
            field=models.CharField(default=b'/', max_length=10000, verbose_name=b'FILE'),
        ),
        migrations.AlterField(
            model_name='icpcheck',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 12, 10, 0, 46, 113668), null=True),
        ),
        migrations.AlterField(
            model_name='subdomainbrute',
            name='fuzz_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 12, 10, 0, 46, 114205), null=True),
        ),
    ]
