# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160712_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burp',
            name='isComplete',
            field=models.IntegerField(default=0, max_length=1, verbose_name=b'isComplete'),
        ),
        migrations.AlterField(
            model_name='icpcheck',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 12, 10, 50, 18, 554272), null=True),
        ),
        migrations.AlterField(
            model_name='subdomainbrute',
            name='fuzz_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 12, 10, 50, 18, 554816), null=True),
        ),
    ]
