# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160712_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpcheck',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 2, 13, 35, 3, 65781), null=True),
        ),
        migrations.AlterField(
            model_name='subdomainbrute',
            name='fuzz_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 2, 13, 35, 3, 66361), null=True),
        ),
    ]
