# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160811_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpcheck',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 11, 16, 17, 38, 288852), null=True),
        ),
        migrations.AlterField(
            model_name='subdomainbrute',
            name='fuzz_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 11, 16, 17, 38, 289680), null=True),
        ),
    ]
